### ISSUE TITLE
Test Failures with Boost > 1.64 on Linux/macOS

### ISSUE THREAD

**Issue by drbenmorgan** [BxCppDev/Bayeux#29]
In seeing whether #20 is resolved by newer Boost versions, I've attempted builds on Bayeux (develop branch) against versions 1.64 through 1.68 on Linux (centos7, gcc7) and macOS (Mojave, Xcode 10). Whilst #20 appears resolved from Boost 1.66 onwards, a slew of other test failures occur, and are reproducible on both platforms (with a couple of differences). The basic steps to reproduce are:

```
$ cmake -DBAYEUX_ENABLE_TESTING=ON <src>
$ make && ctest
```

I have not tested on anything other than the two above systems, but the backtraces suggest this isn't platform/compiler specific.

For Boost 1.65 on Linux only, the following errors occur:

```
	  2 - datatools-test_enriched_base (SEGFAULT)
	 38 - datatools-test_serialization_2 (SEGFAULT)
	 41 - datatools-test_serialization (SEGFAULT)
	165 - brio-test_data_io (SEGFAULT)
	166 - brio-test_brio_writer_1 (SEGFAULT)
	167 - brio-test_brio_reader_1 (SEGFAULT)
	174 - brio-test_reader_3 (SEGFAULT)
	182 - geomtools-test_base_hit (SEGFAULT)
	183 - geomtools-test_blur_spot (SEGFAULT)
	238 - geomtools-test_serializable (SEGFAULT)
	278 - genbb_help-test_primary_event (SEGFAULT)
	326 - mctools-test_base_step_hit (SEGFAULT)
	327 - mctools-test_simulated_data_1 (SEGFAULT)
	345 - mctools-validation_serialization (Failed)
```

Errors apart from 345 have the following backtrace:

```
0x00007ffff029ed69 in std::_Rb_tree_rebalance_for_erase(std::_Rb_tree_node_base*, std::_Rb_tree_node_base&) ()
   from /opt/supernemo/lib/gcc/7/libstdc++.so.6
(gdb) bt
#0  0x00007ffff029ed69 in std::_Rb_tree_rebalance_for_erase(std::_Rb_tree_node_base*, std::_Rb_tree_node_base&) ()
   from /opt/supernemo/lib/gcc/7/libstdc++.so.6
#1  0x00007ffff5e939b7 in boost::serialization::extended_type_info::key_unregister() const ()
   from /opt/supernemo/lib/libboost_serialization-mt.so.1.65.0
#2  0x000000000046e3b0 in boost::serialization::extended_type_info_typeid<genbb::primary_event>::~extended_type_info_typeid (
    this=0x6a0260 <boost::serialization::singleton<boost::serialization::extended_type_info_typeid<genbb::primary_event> >::get_instance()::t>, __in_chrg=<optimized out>) at /opt/supernemo/include/boost/serialization/extended_type_info_typeid.hpp:95
#3  boost::serialization::singleton<boost::serialization::extended_type_info_typeid<genbb::primary_event> >::get_instance()::singleton_wrapper::~singleton_wrapper() (
    this=0x6a0260 <boost::serialization::singleton<boost::serialization::extended_type_info_typeid<genbb::primary_event> >::get_instance()::t>, __in_chrg=<optimized out>) at /opt/supernemo/include/boost/serialization/singleton.hpp:117
#4  0x00007fffef94bb69 in __run_exit_handlers () from /lib64/libc.so.6
#5  0x00007fffef94bbb7 in exit () from /lib64/libc.so.6
#6  0x00007fffef9343dc in __libc_start_main () from /lib64/libc.so.6
#7  0x0000000000469a84 in _start ()
```

These do *not* occur on Boost 1.66-1.67.

From Boost 1.66 onwards, the following tests fail on both macOS and Linux (test numbers are for Linux):

```
	 23 - datatools-test_multi_properties (Child aborted)
	 25 - datatools-test_nans_ar (Child aborted)
	 33 - datatools-test_properties (Child aborted)
	 35 - datatools-test_ser_bitset (Child aborted)
	 39 - datatools-test_serialization_3 (Child aborted)
	 41 - datatools-test_serialization (Child aborted)
	 64 - datatools-test_urn_info (Child aborted)
	 89 - datatools-test_backward_things (Child aborted)
	 93 - datatools-test_event_id (Child aborted)
	117 - mygsl-test_histogram_2d (Child aborted)
	118 - mygsl-test_histogram (Child aborted)
	119 - mygsl-test_histogram_pool (Child aborted)
	337 - mctools-test_signal_signal_data (Child aborted)
	345 - mctools-validation_serialization (Failed)
```

Other than 345, the remainder all appear to be due to the same error, with backtrace for the first test:

```
#0  0x00007fffef99e207 in raise () from /lib64/libc.so.6
#1  0x00007fffef99f8f8 in abort () from /lib64/libc.so.6
#2  0x00007ffff02df1b5 in __gnu_cxx::__verbose_terminate_handler() () from /opt/supernemo/lib/gcc/7/libstdc++.so.6
#3  0x00007ffff02dcfa6 in ?? () from /opt/supernemo/lib/gcc/7/libstdc++.so.6
#4  0x00007ffff02dbf69 in ?? () from /opt/supernemo/lib/gcc/7/libstdc++.so.6
#5  0x00007ffff02dc8d8 in __gxx_personality_v0 () from /opt/supernemo/lib/gcc/7/libstdc++.so.6
#6  0x00007fffefd44f73 in _Unwind_RaiseException_Phase2 (exc=exc@entry=0x85dad0, context=context@entry=0x7fffffffd1b0)
    at ../../../libgcc/unwind.inc:62
#7  0x00007fffefd4579e in _Unwind_Resume (exc=0x85dad0) at ../../../libgcc/unwind.inc:230
#8  0x00007ffff5ef5edb in boost::archive::basic_xml_grammar<char>::my_parse(std::istream&, boost::spirit::classic::rule<boost::spirit::classic::scanner<__gnu_cxx::__normal_iterator<char*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, boost::spirit::classic::scanner_policies<boost::spirit::classic::iteration_policy, boost::spirit::classic::match_policy, boost::spirit::classic::action_policy> >, boost::spirit::classic::nil_t, boost::spirit::classic::nil_t> const&, char) const ()
   from /opt/supernemo/lib/libboost_serialization-mt.so.1.66.0
#9  0x00007ffff5efb140 in boost::archive::xml_iarchive_impl<boost::archive::xml_iarchive>::~xml_iarchive_impl() ()
   from /opt/supernemo/lib/libboost_serialization-mt.so.1.66.0
#10 0x00007ffff6c774f2 in boost::archive::xml_iarchive::~xml_iarchive (this=0x8576e0, __in_chrg=<optimized out>)
    at /opt/supernemo/include/boost/archive/xml_iarchive.hpp:129
#11 boost::archive::xml_iarchive::~xml_iarchive (this=0x8576e0, __in_chrg=<optimized out>)
    at /opt/supernemo/include/boost/archive/xml_iarchive.hpp:129
#12 datatools::io_factory::reset_read_archive (this=0x856d20) at /home/linuxbrew/src/source/bxdatatools/src/io_factory.cc:253
#13 0x00007ffff6c7bea0 in datatools::io_factory::reset (this=this@entry=0x856d20)
    at /home/linuxbrew/src/source/bxdatatools/src/io_factory.cc:479
--Type <RET> for more, q to quit, c to continue without paging--
#14 0x00007ffff6c7bee7 in datatools::io_factory::~io_factory (this=0x856d20, __in_chrg=<optimized out>)
    at /home/linuxbrew/src/source/bxdatatools/src/io_factory.cc:547
#15 0x00007ffff6c7bf39 in datatools::io_reader::~io_reader (this=0x856d20, __in_chrg=<optimized out>)
    at /home/linuxbrew/src/source/bxdatatools/src/io_factory.cc:707
#16 0x00007ffff6c778f3 in datatools::data_reader::reset_reader (this=this@entry=0x7fffffffd8d0)
    at /home/linuxbrew/src/source/bxdatatools/src/io_factory.cc:871
#17 0x00007ffff6c78945 in datatools::data_reader::reset (this=this@entry=0x7fffffffd8d0)
    at /home/linuxbrew/src/source/bxdatatools/src/io_factory.cc:978
#18 0x00007ffff6c7896b in datatools::data_reader::~data_reader (this=0x7fffffffd8d0, __in_chrg=<optimized out>)
    at /home/linuxbrew/src/source/bxdatatools/src/io_factory.cc:766
#19 0x0000000000412205 in main (argc_=<optimized out>, argv_=<optimized out>)
    at /home/linuxbrew/src/source/bxdatatools/testing/test_multi_properties.cxx:109
```

I *suspect* this is caused by boostorg/serialization#109, but the code in io_factory is pretty dense so needs a more knowledgeable eye.

From Boost 1.67.0, the above errors are still present, plus new failures from:

```
	 59 - datatools-test_utils (Failed)
	 65 - datatools-test_urn_db_service (Child aborted)
	 66 - datatools-test_urn_db_service_2 (Child aborted)
	 68 - datatools-test_urn_to_path_resolver_service (Child aborted)
	 69 - datatools-test_urn_query_service (Child aborted)
	 74 - datatools-test_configuration_variant_service (Child aborted)
	 75 - datatools-test_configuration_variant_service_2 (Child aborted)
	 90 - datatools-test_introspection_data_description (Child aborted)
	 91 - datatools-test_introspection_argument (Child aborted)
	 92 - datatools-test_introspection_method (Child aborted)
	337 - mctools-test_signal_signal_data (Child aborted)
	343 - mctools-test_g4_manager (Child aborted)
	344 - bayeux-test_bayeux (Child aborted)
```

The backtrace here is:

```
#0  0x00007fffef99c207 in raise () from /lib64/libc.so.6
#1  0x00007fffef99d8f8 in abort () from /lib64/libc.so.6
#2  0x00007ffff02dd1b5 in __gnu_cxx::__verbose_terminate_handler() () from /opt/supernemo/lib/gcc/7/libstdc++.so.6
#3  0x00007ffff02dafa6 in ?? () from /opt/supernemo/lib/gcc/7/libstdc++.so.6
#4  0x00007ffff02daff1 in std::terminate() () from /opt/supernemo/lib/gcc/7/libstdc++.so.6
#5  0x00007ffff02db233 in __cxa_throw () from /opt/supernemo/lib/gcc/7/libstdc++.so.6
#6  0x00007ffff0303802 in std::__throw_bad_alloc() () from /opt/supernemo/lib/gcc/7/libstdc++.so.6
#7  0x00007ffff6cc0e0d in __gnu_cxx::new_allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >::allocate (this=0x7fffffffd4e0, __n=18446744073709551615)
    at /opt/supernemo/Cellar/gcc@7/7.4.0/include/c++/7.4.0/ext/new_allocator.h:102
#8  std::allocator_traits<std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >::allocate (__a=..., __n=18446744073709551615) at /opt/supernemo/Cellar/gcc@7/7.4.0/include/c++/7.4.0/bits/alloc_traits.h:436
#9  std::_Vector_base<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >::_M_allocate (this=0x7fffffffd4e0, __n=18446744073709551615)
    at /opt/supernemo/Cellar/gcc@7/7.4.0/include/c++/7.4.0/bits/stl_vector.h:172
#10 std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >::_M_range_initialize<char const* const*> (__last=0x0, __first=0x8, 
    this=0x7fffffffd4e0) at /opt/supernemo/Cellar/gcc@7/7.4.0/include/c++/7.4.0/bits/stl_vector.h:1328
#11 std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >::_M_initialize_dispatch<char const* const*> (__last=0x0, 
    __first=0x8, this=0x7fffffffd4e0) at /opt/supernemo/Cellar/gcc@7/7.4.0/include/c++/7.4.0/bits/stl_vector.h:1299
#12 std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >::vector<char const* const*, void> (__a=..., __last=0x0, 
    __first=0x8, this=0x7fffffffd4e0) at /opt/supernemo/Cellar/gcc@7/7.4.0/include/c++/7.4.0/bits/stl_vector.h:414
#13 boost::program_options::basic_command_line_parser<char>::basic_command_line_parser (this=0x7fffffffd730, argc=<optimized out>, 
    argv=0x0) at /opt/supernemo/include/boost/program_options/detail/parsers.hpp:28
#14 0x00007ffff6cb7424 in datatools::kernel::initialize (this=this@entry=0x8386e0, argc_=0, argv_=0x0, flags_=<optimized out>)
    at /home/linuxbrew/src/source/bxdatatools/src/kernel.cc:1144
#15 0x00007ffff6c645a4 in datatools::initialize (argc_=0, argv_=0x0, flags_=flags_@entry=0)
    at /home/linuxbrew/src/source/bxdatatools/src/datatools.cc:50
#16 0x00007ffff6c4b4d9 in bayeux::initialize (argc_=argc_@entry=0, argv_=argv_@entry=0x0, flags_=flags_@entry=0)
    at /home/linuxbrew/src/source/bxbayeux/src/bayeux.cc:89
#17 0x00000000004021e9 in main () at /home/linuxbrew/src/source/bxbayeux/testing/test_bayeux.cxx:26
```

This looks to be down to a `nullptr` being used as `argv`, so not clear if the tests or kernel source is incorrect here.

Boost 1.68.0 has the same set of errors on both platforms as for 1.67, plus on Linux only, the errors in 1.65 reoccur.

Boost 1.69 has not been tested yet as it has interface changes 

SuperNEMO would like to move to a newer Boost version to solve the #20 issue, but the above problems will need fixing first.

**Comment by fmauger** [comment]
This issue is in principle fixed by using Boost 1.69.
